/* This file has been generated from /home/john/Programming/paparazzi.git/conf/airframes/booz2_j1.xml */
/* Please DO NOT EDIT */

#ifndef AIRFRAME_H
#define AIRFRAME_H 

#define AIRFRAME_NAME "BOOZ2_J1"
#define AC_ID 152
#define MD5SUM ((uint8_t*)"\120\327\037\114\364\274\227\103\141\020\305\135\331\021\077\212")

#define SERVOS_NB 4

#define SERVO_FRONT 0
#define SERVO_FRONT_NEUTRAL 0
#define SERVO_FRONT_TRAVEL_UP 0.0265625
#define SERVO_FRONT_TRAVEL_DOWN 0
#define SERVO_FRONT_MAX 255
#define SERVO_FRONT_MIN 0

#define SERVO_BACK 1
#define SERVO_BACK_NEUTRAL 0
#define SERVO_BACK_TRAVEL_UP 0.0265625
#define SERVO_BACK_TRAVEL_DOWN 0
#define SERVO_BACK_MAX 255
#define SERVO_BACK_MIN 0

#define SERVO_RIGHT 2
#define SERVO_RIGHT_NEUTRAL 0
#define SERVO_RIGHT_TRAVEL_UP 0.0265625
#define SERVO_RIGHT_TRAVEL_DOWN 0
#define SERVO_RIGHT_MAX 255
#define SERVO_RIGHT_MIN 0

#define SERVO_LEFT 3
#define SERVO_LEFT_NEUTRAL 0
#define SERVO_LEFT_TRAVEL_UP 0.0265625
#define SERVO_LEFT_TRAVEL_DOWN 0
#define SERVO_LEFT_MAX 255
#define SERVO_LEFT_MIN 0


#define COMMAND_PITCH 0
#define COMMAND_ROLL 1
#define COMMAND_YAW 2
#define COMMAND_THRUST 3
#define COMMANDS_NB 4
#define COMMANDS_FAILSAFE {0,0,0,0}


#define SECTION_BUSS_BLMC 1
#define BUSS_BLMC_ADDR { 0x52, 0x54, 0x56, 0x58 }

#define SECTION_SUPERVISION 1
#define SUPERVISION_FRONT_ROTOR_CW 1
#define SUPERVISION_MIN_MOTOR 2
#define SUPERVISION_MAX_MOTOR 210
#define SUPERVISION_TRIM_A 0
#define SUPERVISION_TRIM_E 0
#define SUPERVISION_TRIM_R 1

#define SECTION_IMU 1
#define IMU_GYRO_P_CHAN 1
#define IMU_GYRO_Q_CHAN 0
#define IMU_GYRO_R_CHAN 2
#define IMU_GYRO_P_NEUTRAL 33026
#define IMU_GYRO_Q_NEUTRAL 32348
#define IMU_GYRO_R_NEUTRAL 32524
#define IMU_GYRO_P_SENS  1.01
#define IMU_GYRO_P_SENS_NUM 101
#define IMU_GYRO_P_SENS_DEN 100
#define IMU_GYRO_Q_SENS -1.01
#define IMU_GYRO_Q_SENS_NUM -101
#define IMU_GYRO_Q_SENS_DEN 100
#define IMU_GYRO_R_SENS -1.01
#define IMU_GYRO_R_SENS_NUM -101
#define IMU_GYRO_R_SENS_DEN 100
#define IMU_ACCEL_X_CHAN 3
#define IMU_ACCEL_Y_CHAN 5
#define IMU_ACCEL_Z_CHAN 6
#define IMU_ACCEL_X_SENS -2.44665442
#define IMU_ACCEL_X_SENS_NUM -69255
#define IMU_ACCEL_X_SENS_DEN 28306
#define IMU_ACCEL_Y_SENS -2.44994081
#define IMU_ACCEL_Y_SENS_NUM -28973
#define IMU_ACCEL_Y_SENS_DEN 11826
#define IMU_ACCEL_Z_SENS -2.50555481
#define IMU_ACCEL_Z_SENS_NUM 18719
#define IMU_ACCEL_Z_SENS_DEN -7471
#define IMU_ACCEL_X_NEUTRAL 32311
#define IMU_ACCEL_Y_NEUTRAL 32536
#define IMU_ACCEL_Z_NEUTRAL 32779
#define IMU_MAG_X_CHAN 4
#define IMU_MAG_Y_CHAN 0
#define IMU_MAG_Z_CHAN 2
#define IMU_MAG_X_NEUTRAL 2129
#define IMU_MAG_Y_NEUTRAL 2327
#define IMU_MAG_Z_NEUTRAL 1817
#define IMU_MAG_X_SENS -3.7152783
#define IMU_MAG_X_SENS_NUM -98923
#define IMU_MAG_X_SENS_DEN 26626
#define IMU_MAG_Y_SENS  3.675688
#define IMU_MAG_Y_SENS_NUM 24175
#define IMU_MAG_Y_SENS_DEN 6577
#define IMU_MAG_Z_SENS -5.02819063
#define IMU_MAG_Z_SENS_NUM 62249
#define IMU_MAG_Z_SENS_DEN -12380
#define IMU_MAG_45_HACK 1
#define IMU_BODY_TO_IMU_PHI ANGLE_BFP_OF_REAL(RadOfDeg(0.75))
#define IMU_BODY_TO_IMU_THETA ANGLE_BFP_OF_REAL(RadOfDeg(1.50))
#define IMU_BODY_TO_IMU_PSI ANGLE_BFP_OF_REAL(RadOfDeg(0.00))

#define SECTION_STABILIZATION_RATE 1
#define BOOZ_STABILIZATION_RATE_SP_MAX_P 10000
#define BOOZ_STABILIZATION_RATE_SP_MAX_Q 10000
#define BOOZ_STABILIZATION_RATE_SP_MAX_R 10000
#define BOOZ_STABILIZATION_RATE_GAIN_P -400
#define BOOZ_STABILIZATION_RATE_GAIN_Q -400
#define BOOZ_STABILIZATION_RATE_GAIN_R -350

#define SECTION_STABILIZATION_ATTITUDE 1
#define BOOZ_STABILIZATION_ATTITUDE_SP_MAX_PHI 3000
#define BOOZ_STABILIZATION_ATTITUDE_SP_MAX_THETA 3000
#define BOOZ_STABILIZATION_ATTITUDE_SP_MAX_R 5500
#define BOOZ_STABILIZATION_ATTITUDE_DEADBAND_R 250
#define BOOZ_STABILIZATION_ATTITUDE_PHI_THETA_PGAIN -400
#define BOOZ_STABILIZATION_ATTITUDE_PHI_THETA_DGAIN -300
#define BOOZ_STABILIZATION_ATTITUDE_PHI_THETA_DDGAIN  300
#define BOOZ_STABILIZATION_ATTITUDE_PHI_THETA_IGAIN -100
#define BOOZ_STABILIZATION_ATTITUDE_PSI_PGAIN -380
#define BOOZ_STABILIZATION_ATTITUDE_PSI_DGAIN -320
#define BOOZ_STABILIZATION_ATTITUDE_PSI_DDGAIN  300
#define BOOZ_STABILIZATION_ATTITUDE_PSI_IGAIN -75

#define SECTION_INS 1
#define BOOZ_INS_BARO_SENS 18.1
#define BOOZ_INS_BARO_SENS_NUM 181
#define BOOZ_INS_BARO_SENS_DEN 10

#define SECTION_GUIDANCE_V 1
#define BOOZ2_GUIDANCE_V_MIN_ERR_Z BOOZ_POS_I_OF_F(-10.)
#define BOOZ2_GUIDANCE_V_MAX_ERR_Z BOOZ_POS_I_OF_F( 10.)
#define BOOZ2_GUIDANCE_V_MIN_ERR_ZD BOOZ_SPEED_I_OF_F(-10.)
#define BOOZ2_GUIDANCE_V_MAX_ERR_ZD BOOZ_SPEED_I_OF_F( 10.)
#define BOOZ2_GUIDANCE_V_HOVER_KP -300
#define BOOZ2_GUIDANCE_V_HOVER_KD -200
#define BOOZ2_GUIDANCE_V_RC_CLIMB_COEF 163
#define BOOZ2_GUIDANCE_V_RC_CLIMB_DEAD_BAND 160000

#define SECTION_GUIDANCE_H 1
#define BOOZ2_GUIDANCE_H_PGAIN -100
#define BOOZ2_GUIDANCE_H_DGAIN -100
#define BOOZ2_GUIDANCE_H_IGAIN -0

#define SECTION_BAT 1
#define MILLIAMP_PER_PERCENT 0.86
#define CATASTROPHIC_BAT_LEVEL 9.3
#define BATTERY_SENS 0.48
#define BATTERY_SENS_NUM 12
#define BATTERY_SENS_DEN 25

#define SECTION_AUTOPILOT 1
#define BOOZ2_MODE_MANUAL BOOZ2_AP_MODE_RATE_DIRECT
#define BOOZ2_MODE_AUTO1 BOOZ2_AP_MODE_RATE_DIRECT
#define BOOZ2_MODE_AUTO2 BOOZ2_AP_MODE_ATTITUDE_DIRECT

#define SECTION_FMS 1

#define SECTION_MISC 1
#define BOOZ2_FACE_REINJ_1 1024


#endif // AIRFRAME_H
