def print_header(name, generatedfrom=None, generatedby=None):
    if generatedfrom:
        print "/* This file has been generated from %s */" % generatedfrom
    if generatedby:
        print "/* This file has been generated by %s */" % generatedby
    print "/* Please DO NOT EDIT */"
    print
    print "#ifndef ", name
    print "#define ", name
    print

def print_footer(name):
    print "\n#endif /* %s */" % name
