ARCHSRC =                                \
    arch/null/null.c

ARCHASMSRC =                             \
    $(NULL)

# Define programs and commands.
CC		    = gcc
LD		    = gcc
OBJCOPY     = objcopy
OBJDUMP     = objdump
SIZE        = size
NM          = nm

GTESTER     = gtester

# Arch specific flags
ARCHCFLAGS  = -g `pkg-config --cflags glib-2.0`
ARCHASFLAGS = 
ARCHLDFLAGS = 

# Flags specific to automated testing
TEST_PROGS = test_math

test_math_SRCS = math/tests/*_tc.c


