/* This file has been generated from /home/john/Programming/paparazzi.gitsvn/conf/airframes/booz2_j1.xml */
/* Please DO NOT EDIT */

#ifndef AIRFRAME_H
#define AIRFRAME_H 

#define MOTORS_NB 4
#define MOTOR_FRONT 0
#define MOTOR_BACK 1
#define MOTOR_RIGHT 2
#define MOTOR_LEFT 3

#define COMMAND_PITCH 0
#define COMMAND_ROLL 1
#define COMMAND_YAW 2
#define COMMAND_THRUST 3
#define COMMANDS_NB 4
#define COMMANDS_FAILSAFE {0,0,0,0}

#define SECTION_BUSS_BLMC 1
#define BUSS_BLMC_ADDR { 0x52, 0x54, 0x56, 0x58 }

#define SECTION_SUPERVISION 1
#define SUPERVISION_FRONT_ROTOR_CW 1
#define SUPERVISION_MIN_MOTOR 2
#define SUPERVISION_MAX_MOTOR 210
#define SUPERVISION_TRIM_A 0
#define SUPERVISION_TRIM_E 0
#define SUPERVISION_TRIM_R 1

#define SECTION_STABILIZATION_RATE 1
#define BOOZ_STABILIZATION_RATE_SP_MAX_P 10000
#define BOOZ_STABILIZATION_RATE_SP_MAX_Q 10000
#define BOOZ_STABILIZATION_RATE_SP_MAX_R 10000
#define BOOZ_STABILIZATION_RATE_GAIN_P -400
#define BOOZ_STABILIZATION_RATE_GAIN_Q -400
#define BOOZ_STABILIZATION_RATE_GAIN_R -350

#define SECTION_STABILIZATION_ATTITUDE 1
#define BOOZ_STABILIZATION_ATTITUDE_SP_MAX_PHI 3000
#define BOOZ_STABILIZATION_ATTITUDE_SP_MAX_THETA 3000
#define BOOZ_STABILIZATION_ATTITUDE_SP_MAX_R 5500
#define BOOZ_STABILIZATION_ATTITUDE_DEADBAND_R 250
#define BOOZ_STABILIZATION_ATTITUDE_PHI_THETA_PGAIN -400
#define BOOZ_STABILIZATION_ATTITUDE_PHI_THETA_DGAIN -300
#define BOOZ_STABILIZATION_ATTITUDE_PHI_THETA_DDGAIN  300
#define BOOZ_STABILIZATION_ATTITUDE_PHI_THETA_IGAIN -200
#define BOOZ_STABILIZATION_ATTITUDE_PSI_PGAIN -380
#define BOOZ_STABILIZATION_ATTITUDE_PSI_DGAIN -320
#define BOOZ_STABILIZATION_ATTITUDE_PSI_DDGAIN  300
#define BOOZ_STABILIZATION_ATTITUDE_PSI_IGAIN -75

#define SECTION_INS 1
#define BOOZ_INS_BARO_SENS 15.
#define BOOZ_INS_BARO_SENS_NUM 15
#define BOOZ_INS_BARO_SENS_DEN 1

#define SECTION_GUIDANCE_V 1
#define BOOZ2_GUIDANCE_V_MIN_ERR_Z BOOZ_POS_I_OF_F(-10.)
#define BOOZ2_GUIDANCE_V_MAX_ERR_Z BOOZ_POS_I_OF_F( 10.)
#define BOOZ2_GUIDANCE_V_MIN_ERR_ZD BOOZ_SPEED_I_OF_F(-10.)
#define BOOZ2_GUIDANCE_V_MAX_ERR_ZD BOOZ_SPEED_I_OF_F( 10.)
#define BOOZ2_GUIDANCE_V_HOVER_KP -300
#define BOOZ2_GUIDANCE_V_HOVER_KD -400
#define BOOZ2_GUIDANCE_V_RC_CLIMB_COEF 163
#define BOOZ2_GUIDANCE_V_RC_CLIMB_DEAD_BAND 160000

#define SECTION_GUIDANCE_H 1
#define BOOZ2_GUIDANCE_H_PGAIN -20
#define BOOZ2_GUIDANCE_H_DGAIN -0
#define BOOZ2_GUIDANCE_H_IGAIN -5

#define SECTION_AUTOPILOT 1
#define BOOZ2_MODE_MANUAL BOOZ2_AP_MODE_RATE_DIRECT
#define BOOZ2_MODE_AUTO1 BOOZ2_AP_MODE_HOVER_DIRECT
#define BOOZ2_MODE_AUTO2 BOOZ2_AP_MODE_ATTITUDE_DIRECT

#define SECTION_MISC 1
#define BOOZ2_FACE_REINJ_1 1024


#endif // AIRFRAME_H
